### ISSUE TITLE
Stable release gives code signin warning

### ISSUE THREAD

**Issue by etique57** [benyanke/docker-nextcloud#3]
Hello,

With the current stable release of the docker image, I get the following warning:
Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the documentation.

Is it intended/inevitable?

Cheers!

**Comment by etique57** [comment]
@benyanke I just tested with your image, change was seamless indeed!

But the issue is still here. I'm using redis, mariadb & solr.

**Comment by benyanke** [comment]
I've seen this in the past as well - NextCloud does hashes of all the files, which is quite nice. Stops some potential for malicious activity where a backdoor would be edited into a file.

Could you attach (redacting sensitive information, if any) the list of files NextCloud thinks are out of place?

**Comment by etique57** [comment]
Using their diagnostic tool, the list is huge... I think it's basically all the files.

**Comment by benyanke** [comment]
hm - have you tried destroying and recreating the container?

**Comment by benyanke** [comment]
Hi @etique57 - any luck with destroying and recreating the container? Just marking this as `closed-stale`, but if you want to jump back on this, reopen the ticket.

**Comment by frankfnord** [comment]
Hey @benyanke I still see this issue. I destroyed the container and recreated it with your current release. 
for me it's basically all files that fail the integrity check. What irritates me is that the code integrity check list of files says "- FILE_MISSING" in each section (core, encryption,files_pdfviewer and so on).

**Comment by benyanke** [comment]
You said the dump is quite long - could you dump it, or at least as much of it as possible, to a text file and upload as an attachment?

Additionally, how are you running the container? Could you provide a copy of your `docker run` statement, your `docker-compose.yml` file, or even a screenshot of the container config (if you're running in a gui tool)?

**Comment by frankfnord** [comment]
[docker-compose.yml.txt](https://github.com/benyanke/docker-nextcloud/files/2061794/docker-compose.yml.txt)
[integrity_check.txt](https://github.com/benyanke/docker-nextcloud/files/2061804/integrity_check.txt)
I attached my docker-compose.yml and the integrity_check.log output. I am running portainer to manage my containers.

**Comment by etique57** [comment]
Sorry @benyanke I dropped the ball, will try this weekend! But I essentially have the same problem as @frankfnord

**Comment by benyanke** [comment]
Thanks for the documentation - well aware of Portainer, excellent tool.

I'll be digging into this deeper...

**Comment by GreenBlood** [comment]
Just adding my two cents here, but I've had this issue regularly after upgrading and rescanning does not help, nor does recreating the container

However when I run " docker run [container] occ integrity:check-core" on the running container and then click "Rescan" on the webpage, the warning disappears.

So my guess is that it might be related with how Nextcloud handles scanning itself through the webpage. Something must break here that does not break with the CLI tool. Maybe because of how Docker mounts the folder and stuff. I don't really know. But I just confirmed the "resolution" of this integrity issue because I upgraded to 13.0.4 a few minutes ago.
Hope it might help

Green.

**Comment by benyanke** [comment]
Well - it seems this is more than an isolated incident, so I think this is a confirmed issue.

What I'm not sure is if it's an issue with the image or with NC - I seem to recall a similar issue when I had a hand-configured VM before I discovered the joys of docker.

Not sure what the next steps are, since there doesn't seem to be any steps to concretely replicate it at this point, but I will hammer on the container a bit, and see what I find.

I'll also keep this ticket open, and please chime in if anyone sees this as well, or has additional helpful information to add.

Thanks all!

**Comment by frankfnord** [comment]
I tried GreenBlood's hint with running the integrity check from the CLI.

```
docker run benyanke/nextcloud:latest occ integrity:check-core
/usr/local/bin/occ: line 2: can't open MEMORY_LIMIT: no such file
```
not sure if that helps..

**Comment by benyanke** [comment]
Has anyone in this thread seen this issue come back since I updated to 13.0.4 4 days ago with `38738f2`?

My suspicion is a nextcloud application issue, not specific to this container image, since as I mentioned above, I've seen it happen to VM and bare-metal installs too occasionally.

I'm going to close out this ticket - but of course I'll reopen for further debugging if we have more confirmed cases.

**Comment by mikedolx** [comment]
Hi, 

it seems that this issue poped up again atleast on my instances.

I am using two instances to run Nextcloud on my Synology NAS. 
 1. reg -> for regression tests
 2. prod -> productive environment

Both instances are spinned up by docker-compose. I wanted to upgrade my prod instance to NC16, by first testing the upgrade process with my reg instance. 

I updated the image tag in my docker-compose file and spinned up the instance with docker-compose up -d. The upgrade seemed to run ok, but i had to disable, remove and reinstall a few apps (the log threw some exceptions during the container startup).

Afterwards i was able to login as admin into the reg instance. After checking the settings i saw that NC was complaining that some files could not be verified due to code signing failure (don't know the exact wording, i'm using german translation).

please find attached my docker-compose file 
[nextcloud_reg_integrity_error.txt](https://github.com/benyanke/docker-nextcloud/files/3227132/nextcloud_reg_integrity_error.txt)
[docker-compose-copy.txt](https://github.com/benyanke/docker-nextcloud/files/3227135/docker-compose-copy.txt)

Any idea, what could be the problem?

**Comment by benyanke** [comment]
Is this a long running install or does it also occur on a clean run of this configured app? I'm seeing a lot of missing files, I wonder if something got deleted in one of your volumes?

**Comment by mikedolx** [comment]
Hi,

this is a "long running install". I used these instances since Nextcloud 13 at least and upgraded them always according to the scheme mentioned above. 

I wouldn't mind making a new clear install, but i'm not sure what i would have to delete in the data volume (without deleting the actual users data).
